#!/usr/bin/env python

import sys

from force_adjustment_plugin.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'force_adjustment_plugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
